# -*- coding: utf-8 -*-
"""most_used_hashtag.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fGgYhwHNolPLEqeZfzU54TUMU_H00A97

# Most used hashtags

### Import data
"""

import os
from google.colab import drive


# tweets folder contains all tweets
drive.mount('/content/drive')
dataset = '/content/drive/My Drive/tweets'
print(dataset)

"""### make counter < hashtag : # tweets >"""

!pip install jsonlines

import glob
import jsonlines
from collections import Counter

hashtags = Counter()
for file in glob.glob(dataset+"/*.jsonl"):
  with jsonlines.open(file) as infile:
      for line in infile:
          for hashtag in line['entities']['hashtags']:
            tag = hashtag['text'].lower()  
            hashtags[tag] += 1

# remove dataset keywords (do not consider possible lower)
del hashtags['coronavirus']
del hashtags['coronaoutbreak']
del hashtags['covid19']

print(f"Total differnt hashtags: {len(hashtags)}")
print(hashtags)

"""### Show most cited domains"""

# print most cited domains
to_show = 40

i = 1
for tag, count in hashtags.most_common(to_show):
    print(f"#{i} => {tag}: {count}")
    i += 1