# -*- coding: utf-8 -*-
"""tweets_distribution.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u9We6MJo-vOIltnk9F8ttY3Arbitu0NG

# Tweets distribution

### Import data
"""

import os
from google.colab import drive


# tweets folder contains all tweets
drive.mount('/content/drive')
dataset = '/content/drive/My Drive/tweets'
print(dataset)

"""### make counter < account : # tweets >"""

!pip install jsonlines

import glob
import jsonlines
from collections import Counter

accounts = Counter()
for file in glob.glob(dataset+"/*.jsonl"):
  with jsonlines.open(file) as infile:
      for line in infile:
          user = line['user']['name']
          accounts[user] += 1

print(f"Unique accounts: {len(accounts)}")
#print(accounts)

"""### Plot distribution"""

from matplotlib  import pyplot as plt

# find distribution
values = accounts.values()

n_tweets = Counter()
for val in values:
    n_tweets[val] += 1


# set params
threshold = 0.9
to_show = 20
to_plot_x = 300
to_plot_y = 300


# print distribution values
X, Y = [], []
found_threshold = False
threshold_val = 0
s = 0
tot = sum(n_tweets.values())

print(f"First {to_show} values: \n")
for x in range(max(values)):
    X.append(x)
    Y.append(n_tweets[x])
    if x < to_show:
        print(f"#{x} {n_tweets[x]}")
    s += n_tweets[x]
    if not found_threshold and s/tot > threshold:
        found_threshold = True
        threshold_val = x

print(f"\n{threshold*100}% of accounts have less than {threshold_val} tweets\n\n")


# adjust plot view
plt.plot(X,Y, color="blue", lw=1.5)
plt.gcf().set_size_inches(10, 10)

plt.xlim((0,to_plot_x))
plt.ylim((0,to_plot_y))

plt.xlabel("# Tweets")
plt.ylabel("# Users")

plt.show()

