# -*- coding: utf-8 -*-
"""accounts_extractor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VytcvpJS0q5Feaf2S-5oMwEJ4Mu-XQYs

# Accounts extractor

### Import data
"""

import os
from google.colab import drive


# tweets folder contains all tweets
drive.mount('/content/drive')
dataset = '/content/drive/My Drive/covid_project/tweets'
to_save = '/content/drive/My Drive/covid_project/graph_files'
print(dataset)

"""### make counter < account : # tweets >"""

!pip install jsonlines

import glob
import jsonlines
from collections import Counter

accounts = Counter()
for file in glob.glob(dataset+"/*.jsonl"):
    with jsonlines.open(file) as infile:
        for line in infile:
            user = line['user']['name']
            accounts[user] += 1

print(f"Total unique accounts: {len(accounts)}")
print(accounts)

import json
import jsonlines

file = to_save + '/accounts.jsonl'

with jsonlines.open(file, mode='w') as outfile:
    for entry in accounts:
      val = {'account':entry, 'tweets':accounts[entry]}
      y = json.dumps(val)
      outfile.write(y)